language: java

deploy:
  script:
    mvn package
  provider: releases
  api_key:
    secure: dCZeul6bCPDbHWBZlonFLSTD9n4Wc0UQHvVXkCWGktQT8NebhyW1G2/x0pX9/pPqhhjq0K24QB57I1XO0IsOw/mz5PyxtlhP48Q4Wulxf3my5/3Wof+VzQCOkEck9Y0W03o1rcXFbU/w99+savo8WOAyqDptOpH4pjlQhLbt+0DJPTMF43Wuh+ZLiFGQNwwjsKVSV7p+Yhju9FUNZqvxonKqfGGfXyKGIytru0pafo2Pl56LZ84ptbuLXkm4PJSZioXqer6/ZqFTkPFLxcOK8WxXgekkCuI6/GEQfek1VhGLpZ5Zh7hgtgEgvMfDBvIR/xGqaFSXTKzJBVGCysNXutsEYpuimIUlGja8jsv5zFgxoAxg1A0taLQLlUA7taQdaVjpK7jEqNb+5WCAlNprxksRWk1fAteBgebRDo9SqRUT/507dkYQDDbkPW8KmmCTj3hsWqj82gMugHFGaJ0aJoMXc1pdayz33Y7+hssrsmArXO2HrHAUjC9jYb4tQnGUe4MBhWw4own/Z7VryGTvGz4eHzNiUJ8oYDiuCLpK/IOoQhYl6XKT+D7WQSQAPIL0DpwuBgnyPzCc7nAaU7iT2ORBjs2vzYR215h4UqKgahDFczUqa4aduRw2i0m7Cwy4MSjzxCYGjgwq1jkzEtVKNR/6caNZIDvR1g2j2Qjn7/I=
  file_glob: true
  file: target/output/*
