name: LightningArrow
version: 1.1.1
api-version: 1.15
main: com.upnorthdevelopers.lightningArrow.LightningArrowPlugin
commands:
  lightningArrow:
    description: Gives user lightning summoning bow
    usage: /lightningArrow
    permission: lightningArrow.shootpl